- name: Extend the logical volume and resize the underlying filesystem
  gather_facts: No
  remote_user: apache
  become: true
  become_method: sudo
  hosts: "{{ Host }}"
  vars_prompt:
  - name: Host
    prompt: "Enter Host ip"
    private: no
  - name: Vgname
    prompt: "Enter VgName"
    private: no
  - name: Lvname
    prompt: "Enter Lvname"
    private: no
  - name: Size
    prompt: "Enter size"
    private: no
  tasks:

  - name: Extend the logical volume resize the underlying filesystem
    community.general.lvol:
      vg: "{{ Vgname }}"
      lv: "{{ Lvname }}"
      size: "{{ Size }}"
      resizefs: true
      force: yes
    register: x

  - debug:
      var: x
   

