- name: Unmount logical volume and remove logical volume
  gather_facts: No
  remote_user: apache
  become: true
  become_method: sudo
  hosts: "{{ Host }}"
  vars_prompt:
  - name: Host
    prompt: "Enter Host ip"
    private: no
  - name: Vgname
    prompt: "Enter VgName"
    private: no
  tasks:
  - name: Remove a volume group 
    community.general.lvg:
      vg: "{{ Vgname }}"
      state: absent
